In [ ]:
# NumPy is a library for the Python programming language, adding support for large, multi-dimensional arrays and matrices,
# along with a large collection of high-level mathematical functions to operate on these arrays.

In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])

print(arr)

[1 2 3 4 5]


In [2]:
for i in arr:
    print(i)

1
2
3
4
5


In [3]:
for i in arr:
    print(i,end=' ') 

1 2 3 4 5 

In [36]:
arr=np.array([1,2,3,4,5])
print(arr.size)

5


In [5]:
# Create an array with 5 zeroes
arr1=np.zeros(5)
print(arr1)

[0. 0. 0. 0. 0.]


In [6]:
# Create an array with 5 ones
arr2=np.ones(5)
print(arr2)

[1. 1. 1. 1. 1.]


In [8]:
#Sorting elements in 1D array
arr=np.array([13,15,10,5,54,36])
print(np.sort(arr))

[ 5 10 13 15 36 54]


In [ ]:
#Slicing an array
#[start:end:step]
#if values not specified then by default [0,len(arr),1]

In [9]:
arr=np.array([1,2,3,4,5,6,7])
print(arr[1:5])

[2 3 4 5]


In [10]:
print(arr[2:])

[3 4 5 6 7]


In [11]:
print(arr[1:5:2])


[2 4]


In [15]:
#Addition operation to array
arr=np.array([1,2,3,4,5])
print(arr)
arr=arr+5
print(arr)

[1 2 3 4 5]
[ 6  7  8  9 10]


In [16]:
#subtraction operation to array
arr=np.array([1,2,3,4,5])
print(arr)
arr=arr-5
print(arr)

[1 2 3 4 5]
[-4 -3 -2 -1  0]


In [17]:
#Multiplication operation to array
arr=np.array([1,2,3,4,5])
print(arr)
arr=arr*5
print(arr)

[1 2 3 4 5]
[ 5 10 15 20 25]


In [19]:
#division operation to array
arr=np.array([5,10,15,20,25])
print(arr)
arr=arr/5
print(arr)

[ 5 10 15 20 25]
[1. 2. 3. 4. 5.]


In [22]:
#Searching an element in array
arr=np.array([1,2,3,4,5,4,4])
x=np.where(arr==4)
print(x)

(array([3, 5, 6], dtype=int64),)


In [24]:
#Find the indexes where values are even
arr=np.array([1,2,3,4,5,6,7,8])
x=np.where(arr%2==0)
print(x)

(array([1, 3, 5, 7], dtype=int64),)


In [25]:
#Filtering: Using a boolen index list
arr=np.array([41,42,43,44])
x=[True,False,True,False]
newarr=arr[x]
print(newarr)

[41 43]


In [31]:
#Check wheather a given array is empty or not
arr=np.array([1,2,3,4,5,6,7,8])
#if len(arr)==0:
if(arr.size ==0):
    print("Empty")
else:
    print("Not empty")
    print(len(arr))

Not empty
8


#### 2D ARRAY

In [32]:
arr=np.array([[1,2,3],[4,5,6]])
print(arr)

[[1 2 3]
 [4 5 6]]


In [34]:
for i in arr:
    print(i)

[1 2 3]
[4 5 6]


In [35]:
#Whenever you want to comput dimension of the array then go for ndim attribute
arr1=np.array([1,2,3,4])
print("Dimension is ",arr1.ndim)
arr2=np.array([[1,2,3],[4,5,6]])
print("Dimension is ",arr2.ndim)

Dimension is  1
Dimension is  2


In [37]:
#Size Attribute
arr=np.array([[1,2,3],[4,5,6]])
print(arr.size)

6


In [40]:
#Shape attribute (to find order)
arr=np.array([[1,2,3,6],[4,5,6,12],[7,8,14,9]])
print(arr.shape)

(3, 4)


In [42]:
#you can also reshape matrix like the above is 3*4
#3*4=12
#6*2=12
#therfore to reshape above matrix 
arr=arr.reshape(6,2)
print(arr)

[[ 1  2]
 [ 3  6]
 [ 4  5]
 [ 6 12]
 [ 7  8]
 [14  9]]


In [43]:
#Create an identity matrix must be a square matrix

#An identity matrix is a square matrix in which all the elements of principal
#diagonals are one, and all other elements are zeros.
arr=np.eye(4)
print(arr)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [45]:
#arange() in python: Used to create array within given range
#Similar to range() function in python
#Syntax: arange([start,] stop[,step,], dtype=None)
arr=np.arange(1,10)
print(arr)

[1 2 3 4 5 6 7 8 9]


In [46]:
arr=np.arange(1,10,2)
print(arr)

[1 3 5 7 9]


In [47]:
#Linspace()
# numpy.linspace(start,
#                stop,
#                num = 50,
#                endpoint = True,
#                retstep = False,
#                dtype = None)


In [ ]:
# -> start  : [optional] start of interval range. By default start = 0
# -> stop   : end of interval range
# -> restep : If True, return (samples, step). By default restep = False
# -> num    : [int, optional] No. of samples to generate
# -> dtype  : type of output array

In [49]:
arr=np.linspace(1,15)
print(arr)

[ 1.          1.28571429  1.57142857  1.85714286  2.14285714  2.42857143
  2.71428571  3.          3.28571429  3.57142857  3.85714286  4.14285714
  4.42857143  4.71428571  5.          5.28571429  5.57142857  5.85714286
  6.14285714  6.42857143  6.71428571  7.          7.28571429  7.57142857
  7.85714286  8.14285714  8.42857143  8.71428571  9.          9.28571429
  9.57142857  9.85714286 10.14285714 10.42857143 10.71428571 11.
 11.28571429 11.57142857 11.85714286 12.14285714 12.42857143 12.71428571
 13.         13.28571429 13.57142857 13.85714286 14.14285714 14.42857143
 14.71428571 15.        ]


In [50]:
arr=np.linspace(1,15,15)
print(arr)

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15.]


In [51]:
#create 1D array with random numbers (numbers are b/w 0 to 1)
arr=np.random.rand(5)
print(arr)

[0.8289472  0.75384606 0.56315008 0.93940018 0.51491536]


In [17]:
#create 2D array with random numbers
arr=np.random.rand(5,3)
print(arr)

[[0.80995414 0.2643509  0.22651061]
 [0.50250146 0.87445816 0.76958528]
 [0.40169402 0.74298127 0.80181397]
 [0.48774572 0.21306895 0.17107104]
 [0.37789896 0.47157245 0.62961366]]


In [21]:
arr1 = np.random.randint(10,90,size=4)
print(arr1)

[24 49 72 82]


In [15]:
arr1 = np.random.randint(10,90,size=(4,5))
arr2 = np.random.randint(10,90,size=(4,5))
print(arr1)
print(arr2)

[[33 59 66 86 25]
 [57 21 15 73 84]
 [60 57 46 11 49]
 [66 18 18 25 88]]
[[10 17 37 65 69]
 [88 18 23 85 13]
 [59 11 16 81 32]
 [80 27 53 22 13]]


In [54]:
#Create a diagonal matrix
arr=np.diag([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


In [2]:
#Flatten a matrix
#transform a matrix into 1D numpy array
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print(arr.flatten())

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 4 5 6 7 8 9]


In [4]:
#Trace of given matrix (Sum of the diagonal elements)
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print("Sum of diagonal elements are ",arr.trace())
print("Sum of diagonal elements are ",sum(arr.diagonal()))

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Sum of diagonal elements are  15
Sum of diagonal elements are  15


In [6]:
arr=np.array([[1,2],[4,5],[7,8]])
print(arr)
print(arr.transpose())

[[1 2]
 [4 5]
 [7 8]]
[[1 4 7]
 [2 5 8]]


In [10]:
arr=np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr)
print("Transpose is \n",arr.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
Transpose is 
 [[1 4 7]
 [2 5 8]
 [3 6 9]]


In [13]:
#Negative indexing to access elements in 2D array
arr=np.array([[1,2,3,4],[5,6,7,8]])
print(arr)
print(arr[1,-1])
#1st parameter is row,second is elment

[[1 2 3 4]
 [5 6 7 8]]
8
